# Generated by Django 4.2.1 on 2023-06-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], max_length=10)),
                ('responsavel', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('etiqueta', models.CharField(choices=[('radio', 'Rádio'), ('telefonia', 'Telefonia'), ('audioevideo', 'Áudio e Vídeo'), ('outros', 'Outros')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
