# Generated by Django 4.2.1 on 2023-06-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
