# Generated by Django 4.2.1 on 2023-06-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacotedespesa',
            old_name='Contrato',
            new_name='contrato',
        ),
        migrations.RemoveField(
            model_name='pacotedespesaequipamentoservico',
            name='contrato',
        ),
    ]
