# Generated by Django 4.2.1 on 2023-06-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_contrato_pacotedespesa_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tasks_cronograma',
            name='cronograma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projetos.cronograma'),
        ),
    ]
