# Generated by Django 4.2.1 on 2023-06-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_created_at_alter_projeto_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DotacaoOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('fonte', models.CharField(max_length=100)),
                ('elemento_item', models.CharField(max_length=100)),
                ('conta', models.CharField(max_length=100)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('documento_ref', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('especificacao', models.TextField(blank=True, null=True)),
                ('codigo_material', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_item', models.CharField(blank=True, max_length=10, null=True)),
                ('elemento_item', models.CharField(blank=True, max_length=8, null=True)),
                ('classe', models.CharField(choices=[('consumo', 'Consumo'), ('permanente', 'Permanente')], max_length=10)),
                ('situacao', models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso')], max_length=20, null=True)),
                ('contrato', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_portal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entrega_instalacao', models.CharField(choices=[('demanda', 'Demanda'), ('licitacao', 'Licitacao'), ('aentregar', 'A entregar'), ('entregue', 'Entregue'), ('ainstalar', 'A instalar'), ('instalado', 'Instalado')], max_length=20)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('local_distribuicao', models.CharField(blank=True, max_length=30, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('arquivos', models.CharField(max_length=100)),
                ('Equipamentos', models.ManyToManyField(to='projetos.equipamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('especificacao', models.TextField(blank=True, null=True)),
                ('codigo_material', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_item', models.CharField(blank=True, max_length=10, null=True)),
                ('elemento_item', models.CharField(blank=True, max_length=10, null=True)),
                ('status_servico', models.CharField(choices=[('realizado', 'Realizado'), ('pendente', 'Pendente')], max_length=20)),
                ('contrato', models.CharField(blank=True, max_length=10, null=True)),
                ('data_servico', models.DateField(blank=True, null=True)),
                ('local_distribuicao', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('emexecucao', 'Em execução'), ('concluido', 'Concluído')], max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20)),
                ('data_inicio_planejada', models.DateField(blank=True, null=True)),
                ('data_fim_planejada', models.DateField(blank=True, null=True)),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PacoteReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(choices=[('radio', 'Rádio'), ('telefonia', 'Telefonia'), ('audioevideo', 'Áudio e Vídeo'), ('outros', 'Outros')], max_length=20)),
                ('natureza_desp', models.CharField(choices=[('custeio', 'Custeio'), ('capital', 'Capital'), ('custeio/capital', 'Custeio/Capital')], max_length=20)),
                ('unid_exec', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('adescentralizar', 'A descentralizar'), ('descentralizado', 'Descentralizado'), ('empenhado', 'Empenhado'), ('liquidado', 'Liquidado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('dot_orc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.dotacaoorcamentaria')),
            ],
        ),
        migrations.CreateModel(
            name='PacoteDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=100)),
                ('esp_fase', models.CharField(blank=True, max_length=100, null=True)),
                ('etiqueta', models.CharField(choices=[('radio', 'Rádio'), ('telefonia', 'Telefonia'), ('audioevideo', 'Áudio e Vídeo'), ('outros', 'Outros')], max_length=20)),
                ('natureza', models.CharField(choices=[('material', 'Material'), ('servico', 'Serviço'), ('materialservico', 'Material/Serviço')], max_length=20)),
                ('beneficiado', models.CharField(blank=True, max_length=100, null=True)),
                ('localizado_em', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('Contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.cronograma')),
                ('dot_orc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.dotacaoorcamentaria')),
                ('equipamentos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.equipamentos')),
                ('orcamentos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.orcamento')),
                ('servicos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.servicos')),
            ],
        ),
        migrations.AddField(
            model_name='orcamento',
            name='Servicos',
            field=models.ManyToManyField(to='projetos.servicos'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='tasks',
            field=models.ManyToManyField(to='projetos.tasks_cronograma'),
        ),
    ]
