# Generated by Django 4.2.1 on 2023-06-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_remove_cronograma_data_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacotedespesa',
            name='beneficiado',
        ),
        migrations.RemoveField(
            model_name='pacotedespesa',
            name='localizado_em',
        ),
        migrations.AddField(
            model_name='pacotedespesa',
            name='contratoend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacotedespesa',
            name='contratoinit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamentoservico',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pacotedespesa',
            name='esp_fase',
            field=models.CharField(blank=True, choices=[('rp-etp', 'Elaboração do ETP'), ('rp-orcamentos', 'Obtenção de Orçamentos'), ('rp-precos', 'Mapa de Preços'), ('rp-autorizacao-dlf', 'Pedido de autorização DLF'), ('rp-gestao', 'Solicitação de Gestão de RP'), ('rp-minuta', 'Elaboração Minuta do Termo de Referência'), ('rp-correcao-minuta', 'Correção Minuta do Termo de Referência (ASSJUR)'), ('rp-correcao-etp', 'Correção ETP (ASSJUR)'), ('rp-formulario-adesao', 'Formulário de Adesão'), ('rp-encaminhado-gol', 'Encaminhado a Gol'), ('rp-impugnacao', 'Respondendo impugnação'), ('rp-resposta-documentacao', 'Resposta a documentação'), ('pg-autorizacao-dlf', 'Pedido de autorização DLF'), ('pg-etp', 'Elaboração do ETP'), ('pg-orcamentos', 'Obtenção de Orçamentos'), ('pg-precos', 'Mapa de Preços'), ('pg-minuta', 'Elaboração Minuta do Termo de Referência'), ('pg-extrato', 'Extrato de Crédito'), ('pg-correcao-minuta', 'Correção Minuta do Termo de Referência (ASSJUR)'), ('pg-correcao-etp', 'Correção ETP (ASSJUR)'), ('Terceiros', 'Terceiros')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacotedespesa',
            name='fase',
            field=models.CharField(blank=True, choices=[('PJ', 'Planejamento'), ('RP', 'RP em andamento'), ('PG', 'PG em andamento'), ('EMP', 'Empenhado'), ('AGE', 'Aguardando entrega'), ('ENT', 'Entregue'), ('INS', 'Instalado')], max_length=100, null=True),
        ),
    ]
