# Generated by Django 4.2.1 on 2023-06-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_remove_pacotedespesa_pacotereceita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoPendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('pendencia', 'Pendência'), ('observacao', 'Observação')], max_length=20)),
                ('data_obs_pend', models.DateField(blank=True, null=True)),
                ('class_obs_pend', models.CharField(choices=[('aconcluir', 'A concluir'), ('concluido', 'Concluído')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pacotedespesa',
            name='cronograma',
        ),
        migrations.RemoveField(
            model_name='pacotedespesa',
            name='esp_fase',
        ),
        migrations.RemoveField(
            model_name='pacotedespesa',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='pacotedespesaequipamentoservico',
            name='situacao',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='pacote_despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='projetos.pacotedespesa'),
        ),
        migrations.AddField(
            model_name='equipamentoservico',
            name='situacao',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pacotedespesa',
            name='status',
            field=models.CharField(blank=True, choices=[('PJ', 'Planejamento'), ('RP', 'RP em andamento'), ('PG', 'PG em andamento'), ('EMP', 'Empenhado'), ('AGE', 'Aguardando entrega'), ('ENT', 'Entregue'), ('INS', 'Instalado')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacotedespesa',
            name='fase',
            field=models.CharField(blank=True, choices=[('rp-etp', 'Elaboração do ETP'), ('rp-orcamentos', 'Obtenção de Orçamentos'), ('rp-precos', 'Mapa de Preços'), ('rp-autorizacao-dlf', 'Pedido de autorização DLF'), ('rp-gestao', 'Solicitação de Gestão de RP'), ('rp-minuta', 'Elaboração Minuta do Termo de Referência'), ('rp-correcao-minuta', 'Correção Minuta do Termo de Referência (ASSJUR)'), ('rp-correcao-etp', 'Correção ETP (ASSJUR)'), ('rp-formulario-adesao', 'Formulário de Adesão'), ('rp-encaminhado-gol', 'Encaminhado a Gol'), ('rp-impugnacao', 'Respondendo impugnação'), ('rp-resposta-documentacao', 'Resposta a documentação'), ('pg-autorizacao-dlf', 'Pedido de autorização DLF'), ('pg-etp', 'Elaboração do ETP'), ('pg-orcamentos', 'Obtenção de Orçamentos'), ('pg-precos', 'Mapa de Preços'), ('pg-minuta', 'Elaboração Minuta do Termo de Referência'), ('pg-extrato', 'Extrato de Crédito'), ('pg-correcao-minuta', 'Correção Minuta do Termo de Referência (ASSJUR)'), ('pg-correcao-etp', 'Correção ETP (ASSJUR)'), ('Terceiros', 'Terceiros')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacotedespesaequipamentoservico',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_equipamento', to='projetos.equipamentoservico'),
        ),
        migrations.AlterField(
            model_name='pacotedespesaequipamentoservico',
            name='pacotedespesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_equipamento', to='projetos.pacotedespesa'),
        ),
    ]
