# Generated by Django 4.2.1 on 2023-06-14 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_observacaopendencia_remove_pacotedespesa_cronograma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacaopendencia',
            name='pacote_despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_pendencias', to='projetos.pacotedespesa'),
        ),
    ]
