# Generated by Django 4.2.1 on 2023-06-15 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_observacaopendencia_pacote_despesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacotedespesa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pacote_despesa', to='projetos.projeto'),
        ),
    ]
