# Generated by Django 4.2.1 on 2023-06-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_alter_pacotedespesa_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacoteAquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('PJ', 'Planejamento'), ('RP', 'RP em andamento'), ('PG', 'PG em andamento'), ('EMP', 'Empenhado'), ('AGE', 'Aguardando entrega'), ('ENT', 'Entregue'), ('INS', 'Instalado')], max_length=100, null=True)),
                ('fase', models.CharField(blank=True, choices=[('rp-etp', 'Elaboração do ETP'), ('rp-orcamentos', 'Obtenção de Orçamentos'), ('rp-precos', 'Mapa de Preços'), ('rp-autorizacao-dlf', 'Pedido de autorização DLF'), ('rp-gestao', 'Solicitação de Gestão de RP'), ('rp-minuta', 'Elaboração Minuta do Termo de Referência'), ('rp-correcao-minuta', 'Correção Minuta do Termo de Referência (ASSJUR)'), ('rp-correcao-etp', 'Correção ETP (ASSJUR)'), ('rp-formulario-adesao', 'Formulário de Adesão'), ('rp-encaminhado-gol', 'Encaminhado a Gol'), ('rp-impugnacao', 'Respondendo impugnação'), ('rp-resposta-documentacao', 'Resposta a documentação'), ('pg-autorizacao-dlf', 'Pedido de autorização DLF'), ('pg-etp', 'Elaboração do ETP'), ('pg-orcamentos', 'Obtenção de Orçamentos'), ('pg-precos', 'Mapa de Preços'), ('pg-minuta', 'Elaboração Minuta do Termo de Referência'), ('pg-extrato', 'Extrato de Crédito'), ('pg-correcao-minuta', 'Correção Minuta do Termo de Referência (ASSJUR)'), ('pg-correcao-etp', 'Correção ETP (ASSJUR)'), ('Terceiros', 'Terceiros')], max_length=100, null=True)),
                ('etiqueta', models.CharField(choices=[('radio', 'Rádio'), ('telefonia', 'Telefonia'), ('audioevideo', 'Áudio e Vídeo'), ('outros', 'Outros')], max_length=20)),
                ('natureza', models.CharField(choices=[('material', 'Material'), ('servico', 'Serviço'), ('materialservico', 'Material/Serviço')], max_length=20)),
                ('contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('contratoinit', models.DateField(blank=True, null=True)),
                ('contratoend', models.DateField(blank=True, null=True)),
                ('doc_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacoteEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(choices=[('radio', 'Rádio'), ('telefonia', 'Telefonia'), ('audioevideo', 'Áudio e Vídeo'), ('outros', 'Outros')], max_length=20)),
                ('natureza_desp', models.CharField(choices=[('custeio', 'Custeio'), ('capital', 'Capital'), ('custeio/capital', 'Custeio/Capital')], max_length=20)),
                ('tipo_pacote', models.CharField(blank=True, choices=[('despesa', 'Despesa'), ('receita', 'Receita')], max_length=20, null=True)),
                ('unid_exec', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('adescentralizar', 'A descentralizar'), ('descentralizado', 'Descentralizado'), ('empenhado', 'Empenhado'), ('liquidado', 'Liquidado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dot_orc', models.ManyToManyField(related_name='pacote_receita_dot_orc', to='projetos.dotacaoorcamentaria')),
            ],
        ),
        migrations.RemoveField(
            model_name='pacotedespesa',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tipo',
        ),
        migrations.RenameModel(
            old_name='PacoteDespesaEquipamentoServico',
            new_name='PacoteAquisicaoEquipamentoServico',
        ),
        migrations.DeleteModel(
            name='PacoteReceita',
        ),
        migrations.AddField(
            model_name='pacoteempenho',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='pacoteaquisicao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pacote_despesa', to='projetos.projeto'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='pacote_despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='projetos.pacoteaquisicao'),
        ),
        migrations.AlterField(
            model_name='observacaopendencia',
            name='pacote_despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_pendencias', to='projetos.pacoteaquisicao'),
        ),
        migrations.AlterField(
            model_name='pacoteaquisicaoequipamentoservico',
            name='pacotedespesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_equipamento', to='projetos.pacoteaquisicao'),
        ),
        migrations.DeleteModel(
            name='PacoteDespesa',
        ),
    ]
