# Generated by Django 4.2.1 on 2023-06-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_pacoteaquisicao_pacoteempenho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacoteaquisicao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pacote_aquisicao', to='projetos.projeto'),
        ),
    ]
