# Generated by Django 4.2.1 on 2023-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_alter_pacoteaquisicao_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamentoservico',
            name='tipo',
        ),
        migrations.AddField(
            model_name='equipamentoservico',
            name='natureza',
            field=models.CharField(choices=[('material', 'Material'), ('servico', 'Serviço'), ('materialservico', 'Material/Serviço')], default='material', max_length=20),
            preserve_default=False,
        ),
    ]
