# Generated by Django 4.2.1 on 2023-07-05 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0012_rename_pacote_despesa_cronograma_pacote_aquisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks_cronograma',
            name='cronograma',
        ),
        migrations.AddField(
            model_name='tasks_cronograma',
            name='pacote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projetos.pacoteaquisicao'),
        ),
        migrations.DeleteModel(
            name='Cronograma',
        ),
    ]
