# Generated by Django 4.2.1 on 2023-08-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_remove_tasks_cronograma_cronograma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotacaoorcamentaria',
            name='documento_ref',
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='pacote_empenho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dotacoes_orcamentarias', to='projetos.pacoteempenho'),
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='unid_benef',
            field=models.CharField(blank=True, choices=[('CSM', '1400011 - CSM'), ('Aj-Geral', '1400005 - Aj-Geral'), ('ABM', '1400017 - ABM'), ('DLF', 'USDO 1400018 - DLF'), ('1ºBBM', '1400006 - 1ºBBM'), ('3ºBBM', '1400008 - 3ºBBM'), ('USDO GOL', '1400018 - USDO GOL'), ('4ºCOB', '1400034 - 4ºCOB'), ('BOA', '1400019 - BOA'), ('2ºCOB', '1400021 - 2ºCOB'), ('8ºBBM', '1400014 - 8ºBBM'), ('5ºBBM', '1400010 - 5ºBBM'), ('12ºBBM', '1400027 - 12ºBBM'), ('3ºCOB', '1400023 - 3ºCOB'), ('5ºCOB', '1400029 - 5ºCOB'), ('6ºCOB', '1400030 - 6ºCOB')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pacoteempenho',
            name='documento_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacoteempenho',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('radio', 'Rádio'), ('telefonia', 'Telefonia'), ('audioevideo', 'Áudio e Vídeo'), ('outros', 'Outros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pacoteempenho',
            name='natureza_desp',
            field=models.CharField(blank=True, choices=[('custeio', 'Custeio'), ('capital', 'Capital'), ('custeio/capital', 'Custeio/Capital')], max_length=20, null=True),
        ),
    ]
