# Generated by Django 4.2.1 on 2023-08-19 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0014_remove_dotacaoorcamentaria_documento_ref_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dotacaoorcamentaria',
            old_name='unid_benef',
            new_name='unid_origem',
        ),
        migrations.RemoveField(
            model_name='pacoteempenho',
            name='doc_ref',
        ),
        migrations.RemoveField(
            model_name='pacoteempenho',
            name='natureza_desp',
        ),
        migrations.RemoveField(
            model_name='pacoteempenho',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pacoteempenho',
            name='unid_exec',
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='divisoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='doc_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='natureza_desp',
            field=models.CharField(blank=True, choices=[('custeio', 'Custeio'), ('capital', 'Capital'), ('custeio/capital', 'Custeio/Capital')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='status',
            field=models.CharField(blank=True, choices=[('adescentralizar', 'A descentralizar'), ('descentralizado', 'Descentralizado'), ('empenhado', 'Empenhado'), ('recolhido', 'Recolhido'), ('remanejado', 'Remanejado'), ('cancelado', 'Cancelado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pacoteempenho',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dotacaoorcamentaria',
            name='acao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dotacaoorcamentaria',
            name='conta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dotacaoorcamentaria',
            name='elemento_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dotacaoorcamentaria',
            name='fonte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoDocacaoOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('env', 'envio'), ('aum', 'aumento'), ('red', 'redução'), ('reb', 'rebalanceamento')], max_length=20)),
                ('detalhamento', models.TextField(blank=True, null=True)),
                ('data_acao', models.DateField(blank=True, null=True)),
                ('pacote_empenho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_dotacoes_orcamentarias', to='projetos.dotacaoorcamentaria')),
            ],
        ),
    ]
