# Generated by Django 4.2.1 on 2023-08-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_rename_unid_benef_dotacaoorcamentaria_unid_origem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotacaoorcamentaria',
            name='divisoes',
        ),
        migrations.AddField(
            model_name='dotacaoorcamentaria',
            name='unid_destino',
            field=models.CharField(blank=True, choices=[('CSM', '1400011 - CSM'), ('Aj-Geral', '1400005 - Aj-Geral'), ('ABM', '1400017 - ABM'), ('DLF', 'USDO 1400018 - DLF'), ('1ºBBM', '1400006 - 1ºBBM'), ('3ºBBM', '1400008 - 3ºBBM'), ('USDO GOL', '1400018 - USDO GOL'), ('4ºCOB', '1400034 - 4ºCOB'), ('BOA', '1400019 - BOA'), ('2ºCOB', '1400021 - 2ºCOB'), ('8ºBBM', '1400014 - 8ºBBM'), ('5ºBBM', '1400010 - 5ºBBM'), ('12ºBBM', '1400027 - 12ºBBM'), ('3ºCOB', '1400023 - 3ºCOB'), ('5ºCOB', '1400029 - 5ºCOB'), ('6ºCOB', '1400030 - 6ºCOB')], max_length=50, null=True),
        ),
    ]
