# Generated by Django 4.2.4 on 2023-12-02 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0016_remove_dotacaoorcamentaria_divisoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacoteaquisicaoequipamentoservico',
            name='pacotedespesa',
        ),
        migrations.RemoveField(
            model_name='pacoteempenho',
            name='dot_orc',
        ),
        migrations.RemoveField(
            model_name='pacoteempenho',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='pacoteaquisicaoequipamentoservico',
            name='pacoteaquisicao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='aquisicao_equipamento', to='projetos.pacoteaquisicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacoteempenho',
            name='natureza',
            field=models.CharField(choices=[('material', 'Material'), ('servico', 'Serviço'), ('materialservico', 'Material/Serviço')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
