# Generated by Django 4.2.4 on 2023-12-03 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0018_dotacaoorcamentaria_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacoteempenho',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pacote_empenho', to='projetos.projeto'),
        ),
    ]
