# Generated by Django 4.2.4 on 2023-12-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0019_alter_pacoteempenho_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacoteaquisicao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_aquisicao', to='projetos.projeto'),
        ),
        migrations.AlterField(
            model_name='pacoteempenho',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_empenho', to='projetos.projeto'),
        ),
    ]
